version: '3'

services:
  app_db:
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/postgresql/db_data
    environment:
      - POSTGRES_DB=pollsapp
      - POSTGRES_USER=syengo
      - POSTGRES_PASSWORD=password123

  app_django:
    build: .
    working_dir: /code
    environment:
      - POSTGRES_DB=pollsapp
      - POSTGRES_USER=syengo
      - POSTGRES_PASSWORD=password123
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - app_db
